### ISSUE TITLE
File names with underscore in them

### ISSUE THREAD

**Issue by unimonkiez** [bignimbus/import-resolve#3]
Hey,
Great repo, needed something like that for a long time.
Was just about to fix the issue when I import a file like so:
```sass
@import './bla';
```
but the actual file name is `_bla.scss` for instance and it couldn't find it, but found out it been fixed already ([here](https://github.com/bignimbus/import-resolve/blob/master/index.js#L66)).  
Do you care to upload a new version to npm?   
Thanks in advance.

**Comment by bignimbus** [comment]
Fixed in version 0.2.7 - thanks!
