### ISSUE TITLE
Can't concat bootstrap ..

### ISSUE THREAD

**Issue by firatsarlar** [bignimbus/import-resolve#5]
I'm trying to concat bootstrap ( v4. alpha 5 )
giving main bootstrap file ( which imports all other mixins, vars etc ) 
this cause an infinitive loop, 

to reproduce ..

in a new dir 

npm install bootstrap@next ( which is v4. alpha5 currently )

importResolve({
    "ext": scss,
    "pathToMain": node_modules/bootstrap/scss/bootstrap.scss,
     "output": ./out.scss
});

**Comment by bignimbus** [comment]
@firatsarlar Thanks for the report.  I'm going to try to reproduce this soon and I'll let you know what I find!

In the meantime, could you give me more information about your setup?

Node version: ___
Operating System: ___

**Comment by bignimbus** [comment]
@firatsarlar I believe I found the issue.

The regular expression used to capture `@import` appears to be grabbing a commented piece of code in a bootstrap SCSS module.  This causes import-resolve to recursively resolve the bootstrap main file, resulting in an infinite loop.

- [See here for the import-resolve regular expression](https://github.com/bignimbus/import-resolve/blob/master/lib/import-resolver.js#L5)
- [See here for the line in the bootstrap source](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L47)

Note that if you delete the line in question in the bootstrap source code, the infinite loop no longer occurs.

If you have to put out this fire immediately, I recommend deleting that comment from the bootstrap source code in your `node_modules` folder.

But this is also a deficiency that I will patch in `import-resolve` in the near future.  Thanks much.

**Comment by firatsarlar** [comment]
Thanks for fast response.
I'll try to remove commented line .    
I think I solved the issue .

`    regex = /^@import[^'"]+?['"](.+?)['"];?/gm; `

adding ^( start of line ) and m flag ( multiline ) solved issue 
page below I used to  test regex .
https://regex101.com/r/bnmPMo/1

( I would like to make a pull request but it should be easier for you to changing that line ) (I'm not practically familiar git workflows )

**Comment by firatsarlar** [comment]
My mistake
Regex should also allow whitespace ( \s* ) after starting new line.
```js regex = /^\s*@import[^'"]+?['"](.+?)['"];?/gm; ````

To see tests 
https://regex101.com/r/bnmPMo/2

**Comment by bignimbus** [comment]
@firatsarlar thanks for the suggestion.  I looked into the regular expression you wrote, and ran into this issue:

```js
regex = /^\s*@import[^'"]+?['"](.+?)['"];?/gm;
regex.test(".namespace { @import 'namespace-styles' }")
// false
```

Not all valid `@import` statements are necessarily at the beginning of a new line.  I think what will end up needing to be done is to write the following functions that return booleans:

1. Is the import statement preceded by `/*` and succeeded by `*/`? (multiline included)
2. On the same line as the import statement, does `//` appear to the left of it?

Once those tests pass, I think this bug will be fixed.

Thanks so much for the bug report and for the suggestion, it's very helpful.

**Comment by firatsarlar** [comment]
**@bignimbus** 
My bad, I did not know spec about imports ( also I was looking at problem  in sass context, but there are  others you cover as stylus, less, css ..

Since lookbehind is not supported in js, one way is extra checks as you said , or extend regex to capture non commented lines ( but it's hard because of multiline comments )

By the way I could not see regex tests in tests section . 

Anyway I just wanted to contribute a quick fix. Currently it needs extra effort.

Thanks.

**Comment by bignimbus** [comment]
Thanks @firatsarlar, I will pull this down soon and check into it.

**Comment by bignimbus** [comment]
@firatsarlar I merged two of your three pull requests.  I think adding the "ignore comments" feature is enough to bump `import-resolve` to `0.4.0`.  The CLI should bring us to `0.5.0` pending documentation.

**Comment by firatsarlar** [comment]
@bignimbus Ok, thank you.
